spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paramount?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: gentoo666
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: localhost
    port: 6379
    maxIdle: 300
    maxWait: 3000
    testOnBorrow: true
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: 17673125001
    password: gentoo111
    protocol: smtp
    test-connection: false
  data:
      solr:
        host: http://localhost:8983/solr
        core: tbitem
mybatis:
  type-aliases-package: com.paramount.admin.domain
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
files:
  path: ${file-path:d:/files}
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/admin-server.log
  maxsize: 300MB
token:
  expire:
    seconds: 86400
server:
  port: 9000
# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
FILE_SERVER_URL: http://192.168.209.133/
appid: wx8397f8696b538317
partner: 1473426802
partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
notifyurl: http://a31ef7db.ngrok.io/WeChatPay/WeChatPayNotify
pagedir: pagedir
ENDPOINT: http://oss-ap-southeast-1.aliyuncs.com
ACCESS_KEY_ID: LTAIOprLJ23TFyBI
ACCESS_KEY_SECRET: JKo9s0YgY372FK5C8Heejrkwf2FdB6
BUCKET_NAME: boxlot-product-private